ci(deploy): prevent creation of existing directories
Added a check in `deploy.yml` to ensure the target directory does not already exist before attempting to create it. This prevents accidental overwriting or conflict errors during deployment.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -84,7 +84,12 @@ jobs:
       - name: Deploy to Server
         run: |
           ssh -o StrictHostKeyChecking=no ${{ env.REMOTE_HOST_USER }}@${{ env.REMOTE_HOST_NAME }} <<EOF
-            mkdir -pv ${{ env.REMOTE_HOST_PATH }}~${{ env.CURRENT_REFERENCE }}/logs
+            if [ -d "${{ env.REMOTE_HOST_PATH }}~${{ env.CURRENT_REFERENCE }}" ]; then
+              echo "Error: Directory ${{ env.REMOTE_HOST_PATH }}~${{ env.CURRENT_REFERENCE }} already exists." >&2
+              exit 1
+            else
+              mkdir -pv ${{ env.REMOTE_HOST_PATH }}~${{ env.CURRENT_REFERENCE }}/logs
+            fi
           EOF
 
           # Remove SQLite database files
